version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: skill-app
    restart: on-failure
    ports:
     - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/enaaskills?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
    depends_on:
    - db
    networks:
    - skill_network

  db:
   image: mysql:8.0
   environment:
    MYSQL_DATABASE: enaaskills
    MYSQL_ROOT_PASSWORD:
    MYSQL_ALLOW_EMPTY_PASSWORD: true
   ports:
   - "3306:3306"
   volumes:
   - db_data:/var/lib/mysql
   networks:
   - skill_network

networks:
  skill_network:
    driver: bridge

volumes:
  db_data: